yang_bo_dream_blog_homepage:
    path: /
    defaults:
        _controller: YangBoDreamBlogBundle:Default:index

yang_bo_dream_blog_article:
    resource: '@YangBoDreamBlogBundle/Resources/config/routing/article.yml'
    prefix: /article

yang_bo_dream_blog_tag:
    resource: '@YangBoDreamBlogBundle/Resources/config/routing/tag.yml'
    prefix: /tag

yang_bo_dream_blog_admin:
    resource: '@YangBoDreamBlogBundle/Resources/config/routing/admin.yml'
    prefix: /admin