yang_bo_dream_blog_admin_login_check:
    path: /login_check

yang_bo_dream_blog_admin_login:
    path: /login
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:login

yang_bo_dream_blog_admin_logout:
    path: /logout

yang_bo_dream_blog_admin_main:
    path: /main
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:main

yang_bo_dream_blog_admin_system:
    path: /system
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:system

yang_bo_dream_blog_admin_category:
    path: /category
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:category

yang_bo_dream_blog_admin_category_tree:
    path: /category/tree
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:categoryTree

yang_bo_dream_blog_admin_category_add:
    path: /category/add
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:categoryAdd

yang_bo_dream_blog_admin_category_update:
    path: /category/update
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:categoryUpdate

yang_bo_dream_blog_admin_category_detail:
    path: /category/detail/{id}
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:categoryDetail

yang_bo_dream_blog_admin_category_delete:
    path: /category/delete
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:categoryDelete
yang_bo_dream_blog_admin_test:
    path: /test
    defaults:
        _controller: YangBoDreamBlogBundle:Admin:test